<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class AsignacionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('asignacions')->truncate();
        
        DB::table('asignacions')->insert(['codigo' => 'A003','description' => 'PRIMA ANTIGUEDAD','monto'=>'0.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A005','description' => 'BONO ALIMENTICIO','monto'=>'2'],);
 		DB::table('asignacions')->insert(['codigo' => 'A007','description' => 'BONO DE TRANSPORTE Y ALIMENTA','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A013','description' => 'PRIMA POR HOGAR','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A017','description' => 'BONO ASISTENCIAL','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A021','description' => 'PRIMA TITULAR','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A026','description' => 'RECONOC. PRODUCTIVIDAD','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A025','description' => 'PRIMA ANTIGUEDAD','monto'=>'1.5'],); //REPERTIDA	
		DB::table('asignacions')->insert(['codigo' => 'A022','description' => 'BONO NAVIDEÑO','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A023','description' => 'DIF. PRIMA MATRIMONIO','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A024','description' => 'PRIMA ESPECIAL HIJO','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A027','description' => 'BECA','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A029','description' => 'JERARQUIA 1ERA. QNA.','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A030','description' => 'PRIMA APOYO DOC. INVEST.','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A031','description' => 'PAGO PRIMA','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A033','description' => 'PROMEDIO PRIMA CARGO','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'FA03','description' => 'AYUD. PARA INCRIP. Y UNIFORMES','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A035','description' => 'DIF.ASIG.COMPL. ENE.-ABRIL 99','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A036','description' => 'REINT.INCENT/EST.','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A002','description' => 'PENSION POR JUBILACION','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A004','description' => 'PENSION POR INCAPACIDAD','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A010','description' => 'BONO ALIMENTICIO','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A011','description' => 'BONO ALIMENTICIO BONO FIN DE AÑO','monto'=>'1.5'],);
		DB::table('asignacions')->insert(['codigo' => 'A016','description' => 'PRIMA DE JERARQUIA 45 DIAS','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A014','description' => 'PRIMA PROFESIONAL','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A018','description' => 'BONO DOCTOR 2003','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A019','description' => 'DIF/BONO ASISTENCIAL DIC.99','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A020','description' => 'INTERESES S/PRESTACIONES','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A006','description' => 'PRIMA DE HIJO BONO FIN DE AÑO','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A008','description' => 'HOGAR 45 DIAS BONO VACACIONAL','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A037','description' => 'PRIMA TITULAR 45 DIAS B/F.ANO','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A038','description' => 'REINT. SSO AGOSTO-SEPT. 2002','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A039','description' => 'PRIMA 45 DIAS','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A040','description' => 'REINT/IPAS-ME AGOSTO-SEPT.2002','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A0FA','description' => 'DIF. PRIMA ANTIGUEDAD','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A043','description' => 'REINT. LEY HAB/AGOST-SEPT.2002','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A044','description' => 'DIF.PRIMA NACIMIENTO','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A045','description' => 'REINT.I.S.L.R/AGOSTO-SEPT.2002','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A046','description' => 'DIF/SUELDO FEBRERO-ABRIL 99','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A047','description' => 'BONO UNICO','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'D053','description' => 'LIBRERIA AMERICA','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'D055','description' => 'SEGURO DE VIDA','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A049','description' => 'DIF/COMP.AJ.TABUL/ENERO-JUN/98','monto'=>'1.8'],);
		DB::table('asignacions')->insert(['codigo' => 'A050','description' => 'DIFERENCIA SUELDO ENERO','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A051','description' => 'REINT.DESC.IND.BOUTIQUE ENE.99','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A053','description' => 'DIF/BONO ASIST/FEB-ABRIL 99','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A054','description' => 'BENEF.VASO LECHE','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A055','description' => 'PRIMA PROFES/FEBRERO-ABRIL 99','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A056','description' => 'DIF.PJER.DEL 19-01 AL 27-2-99','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A057','description' => '9.5 DIAS','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A058','description' => 'DIF/BONO ASIST.19-1 AL 31-1-98','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A059','description' => 'PRIMA JERARQUIA','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A061','description' => 'DIF/BONO ASISTENCIAL','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'FFD0','description' => 'PAGO INDEB.PHIJO JUL-NOV.2000','monto'=>'1.8']);	
		DB::table('asignacions')->insert(['codigo' => 'A062','description' => 'DIF/PRIMA JERARQUIA ENERO 2003','monto'=>'1.8']);		
		DB::table('asignacions')->insert(['codigo' => 'A063','description' => 'DIF/JERARQ/DEL 25-3 AL 31-3-03','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A064','description' => 'PRIMA DE PROFESINALIZACION','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A065','description' => 'BONO/VACACIONAL','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A066','description' => 'BONO FIN DE AÑO','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A067','description' => 'DIF. 9.5 DIAS','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A068','description' => 'PRIMA HIJO ESPECIAL BONO FANO','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A069','description' => 'HIJO ESPECIAL BONO F/A.','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A070','description' => 'PRIMA HIJO BONO VACAC.','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A071','description' => 'PRIMA HOGAR BONO FIN DE ANO','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A072','description' => 'PRIMA TITULAR ENE-FEB. 1999','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A073','description' => 'DIF.PRIMA/PROF/E.F.M.A.J.A.S.','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A074','description' => 'DIF. SUELDO ENE-FEB. 1999','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A075','description' => 'RNT/PAGO IND/C.EXT.ASETA FEB.','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A076','description' => 'DIF. ASIG.COMPL. ENE-FEB. 1999','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A077','description' => 'P/TITULAR FEB-MAR. 1999','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A078','description' => 'PRIMA JERARQ. 2DA. QNA. ENERO','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A079','description' => 'PRIMA HIJO 45 DIAS BONO VAC.','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A080','description' => 'PRIMA HIJO 45 DIAS BONO/F.ANO','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A900','description' => 'DIF/SUELDO ENERO-ABRIL 99','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A081','description' => 'DIF. SUELDO ENE-MAR. 1999','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A083','description' => 'BONO NOCTURNO','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A084','description' => 'BONO ASISTENCIAL 45 DIAS','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A085','description' => 'RETROAC. PRIMA HIJO ENERO 2000','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A086','description' => 'BONO DE DOCTOR','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A087','description' => 'ASIG. COMPL. POR ACT.ACADEMICA','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A088','description' => 'DIF. PRIMA TITULAR','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A089','description' => 'DIF. PRIMA JERARQUIA','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A091','description' => 'DIF. 9.5 DIAS','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A092','description' => 'INTERES PRESTACIONES 43.72%','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A093','description' => 'DIF. BONO FIN DE AÑO','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A094','description' => 'ASIGNACION ESPECIAL 45 DIAS','monto'=>'1.8']);
		DB::table('asignacions')->insert(['codigo' => 'A095','description' => 'PROMEDIO PRIMA CARGO 45 DIAS','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A096','description' => 'DIF. PRIMA ESPECIAL HIJO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A097','description' => 'DIF. BONO ASISTENCIAL 45 DIAS','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A098','description' => 'REINT. FONDO DE JUB. JULIO 03','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A099','description' => 'DIF. PRIMA HIJO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A100','description' => 'BONO UNICO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A101','description' => 'DIF. JERARQUIA 45 DIAS','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A102','description' => 'RETROAC. PJER.','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A103','description' => 'UTILES ESCOLARES','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A104','description' => 'BECA','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A105','description' => 'DOTACION DE UNIFORMES','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A106','description' => 'DIF/SUELDO MAYO-JUNIO 99','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A107','description' => 'DIF/BONO ASIST/MAYO-JUNIO 1999','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A108','description' => 'DIF/SUELDO MAYO 99','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A109','description' => 'DIF/BONO ASISTENC/MAYO 1999','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A110','description' => 'RTE.DCTO.IND.PREST.C.ENERO 93','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A111','description' => 'DIF. PRIMA TITULAR NOV. 99','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A112','description' => 'ASIGNACION POR FALLECIMIENTO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A113','description' => 'PRIMA JERARQUIA OCT. 99','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A114','description' => 'JUGUETES','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A115','description' => 'HORAS EXTRAS','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A116','description' => '5 DIAS DE SALARIO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A117','description' => 'REINTEGRO AYUDA MUTUA','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A417','description' => 'PENSION HORAS EXTRAS','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A118','description' => 'DIF.PRIMA HOGAR ENE-MAYO 2012','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A119','description' => 'REINTEGRO','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A120','description' => 'RET.P/JERARQ. JUL.AGO.SEPT.96','monto'=>'2.0']);	
		DB::table('asignacions')->insert(['codigo' => 'A121','description' => 'DIF. PJERARQUIA JULIO 99','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A122','description' => 'RNT.DTO.IND.SOC.C.MAT.SEPT.93','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A123','description' => 'RETROACTIVO SUELDO','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A082','description' => 'PRIMA TITULAR FEBRERO 1999','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A090','description' => 'DIF. BONO VACACIONAL','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A125','description' => 'RETROACTIVO P/PROFESIONAL','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A124','description' => 'RETROACTIVO P/ HIJO','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A126','description' => 'DIF.8.5 INTER/PRESTAC.','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A128','description' => 'REINT.PRIMA/ANTIG.FEB.MARZO 94','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A127','description' => 'RET.DECT.IND.CSINDIC.MAR.95','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A129','description' => 'REINTEGRO HCM E.F.M. 94','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A130','description' => 'REINT. SEGURO DE VIDA F.M 94','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A131','description' => 'AJUSTE SALARIAL CONVENIO 94/95','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A132','description' => 'COMPENSACION SALARIAL','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A012','description' => 'PRIMA POR HIJO','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A134','description' => 'RETROACT.P/HIJO ENERO-MARZO 94','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A135','description' => 'REINT.SEGURO DE VIDA ABRIL 94','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A133','description' => 'DIF. MENSUAL DE SUELDO','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A136','description' => 'DIF. PRIMA DE TITULAR','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A137','description' => 'DIF. PRIMA POR HOGAR','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A138','description' => 'DIF. PRIMA POR HIJO','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A139','description' => 'DIF. ASIG.COMP. ACTUALIZ.ACAD.','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A140','description' => 'DIF. PRIMA ASISTENCIAL','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A141','description' => 'DIF. PRIMA DE PROFESIONALIZAC.','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A142','description' => 'RETRO.ANTIGUEDAD MAYO 94','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A143','description' => 'RETRO.ANTIGUEDAD ENE-ABRL.94','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A144','description' => 'RET. PRIMA HIJO AGO. SEPT 96','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A145','description' => 'DIF. P/TITULAR NOV. 94','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A160','description' => 'RET.DTO.IND.HCM DIF.EN.MAR.94','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A161','description' => 'DIF.PRIMA ESPEC.HIJO JUNIO 94','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A146','description' => 'BONO NOCTURNO','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A170','description' => 'DIF. B/CHOFER B/VAC. 2001','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A171','description' => 'DIF.B/CHOFER B/FIN DE AÑO 2001','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A162','description' => 'DIFERENC.PRIMA ANTIG.OCT.94','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A163','description' => 'DIF.PRIMA/JERARQ.MES OCT.94','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A147','description' => 'DIF. BONO DE 35 DIAS','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A164','description' => 'RET.PROM.PCARGO ENERO 95','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A165','description' => 'REINT.PAGO INDEB.SSO ENERO 95','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'FD11','description' => 'PENS/ALIM/INT/S/PRESTAC/SOC.95','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A166','description' => 'INT.SOBRE PRESTACIONES S.1994','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A148','description' => 'DIF. PRIMA HIJO ABRIL 95','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A149','description' => 'DIF. PRIMA TITULAR MAYO 1995','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A418','description' => 'PENSION P/GRADO ACADEMICO','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A151','description' => 'BONO ALIMENTICIO BONO VACACION','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A152','description' => 'BONO ALIMENTICIO BONO FIN DE A','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A172','description' => 'BONO NOCTURNO ENERO -JULIO 95.','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A173','description' => 'BONO NOCTURNO.','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A174','description' => 'DIF.P/TITULAR ABRIL-MAY-JUN 95','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A175','description' => 'DIF. P/TITULAR JULIO 95','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A176','description' => 'P/HIJO JULIO 95','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A177','description' => 'PRIMA JERARQUIA JULIO 95','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A153','description' => 'RET.ASIGNACION ESPC.JUNIO 95','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A178','description' => 'RET.CESTA NAVIDENA AGOSTO 95','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A167','description' => 'APORTE SEGUN CLAUSULA 74','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A180','description' => 'DIFERENC/BECAS 97','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A179','description' => 'DIF.BONO FIN DE ANO','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A181','description' => 'REINT/DCTO/LETRA IPASME OC-NOV','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A182','description' => 'RELACION ALMUERZOS','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A183','description' => 'REINT/PRIMA ANTIGUEDAD ENERO','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A184','description' => 'REINT/PRIMA HIJO ENERO','monto'=>'2.0']);
		DB::table('asignacions')->insert(['codigo' => 'A185','description' => 'RET.DESC.IND.PREST.CAPPAOUPEL','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A186','description' => 'RETROC. PHIJO AGOST-SEP. 99','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A187','description' => 'REINT. POR DCTO/INDEB.ENERO 96','monto'=>'2']);	
		DB::table('asignacions')->insert(['codigo' => 'A190','description' => 'RET. H.C.M. JULIO-DIC. 98','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A191','description' => 'RET/DCTO/IND/CAPPAOPUEL J-SEPT','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A192','description' => 'RET/DCTO/IND/CAPPAOUPEL J-OCT.','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A193','description' => 'RET/DCTO/IND/CAPPAOUPEL J-NOV.','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A194','description' => 'RET/DTO/IND/CAPPAOPUEL J-DIC.','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A195','description' => 'RET.DESC.IND.PRIM.ANTG.FEB.96','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A196','description' => 'JERARQUIA 2DA QNA. DE MARZO','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A168','description' => 'LAPSO DE PAGO:1-10 AL 31-12-94','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A169','description' => 'LAPSO DE PAGO:1-11 AL 31-12-94','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A188','description' => 'LAPSO DE PAGO:24-10 /31-12-94','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A197','description' => 'DIF. P/JERARQ. 2DA.QNA. MAY.96','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A198','description' => 'DIF. PRIMA HIJO JUNIO 96','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => '0D18','description' => 'APORTE PROFESION/MES JUNIO 96','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A199','description' => 'PRIMA MENSAJERIA EXTERNA','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A200','description' => 'REINT.I.S.L.R. JULIO 2003','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A154','description' => 'DIF. PRIMA HIJO SEPT.OCT. 96','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A201','description' => 'DIF/BONIF/FIN DE AÑO P/TITULA','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A202','description' => 'REINT.DESC.IND.BOUTIQUE OCT 97','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A203','description' => 'PRIMA TITULAR NOVIEMBRE 96','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A204','description' => 'RET. PRIMA HOGAR ENE-DIC 96','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A205','description' => 'RET.DIF. PRIMA HOGAR BONO VAC.','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A206','description' => 'RET.DIF. PRIMA HOGAR BONO F/A','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A207','description' => 'RET.DIF. PRIMA HOGAR 9.5 DIAS','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A208','description' => 'RET. PRIMA HIJO ENERO-DIC. 96','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A209','description' => 'RET.DIF. PRIMA HIJO BONO VAC.','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A210','description' => 'RET.DIF. PRIMA HIJO BONO F/A','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A211','description' => 'RET.DIF. PRIMA HIJO 9.5 DIAS','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A212','description' => 'RET.DIF.PRIMA ANTIG.ENE-DIC.96','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A213','description' => 'RET.DIF.PRIMA ANTIG.BONO VAC.','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A214','description' => 'RET.DIF.PRIMA ANTIG.BONO F/A.','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A216','description' => 'RETROACT/P/HIJO ENERO 1997','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A217','description' => 'RETROAC.LEY HABITAC/ENERO 1997','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A218','description' => 'RETROACT/PARO FORZ/ENERO 1997','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A215','description' => 'MONTO ACUERDO FEDERATIVO 1996','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A219','description' => 'DIF.ASICOMPACT.ACADAB-JUL97','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A230','description' => 'MONTO UNICO','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A231','description' => 'MONTO','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A220','description' => 'DEF. ASIG.COMPL.EN-FE-JU-AGO.97','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A232','description' => 'REINTEGRO MEDICINAS','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'D192','description' => 'CUOTA EXTRAORDIN.CAPPAOUPEL','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'FA22','description' => 'DIF. PHIJO JUL.-OCTUBRE 97','monto'=>'2']);
		DB::table('asignacions')->insert(['codigo' => 'A222','description' => 'DIF.SALARIO MARZO-ABRIL 1999','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A221','description' => 'DIF.PHIJO JUL.OCTUBRE 97','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A75','description' => 'REINT.MEDICINAS MES JULIO 97','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A236','description' => '9.5 DIAS','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A237','description' => 'APORTE INSTITUCION. CAPAUPEL','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A223','description' => 'REIT.DESC.IND.LEY HAB.DIC.97','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A224','description' => 'REINT.DESC.IND.S.S.O.97','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A225','description' => 'DIF.SUELDO MES ENERO 1998','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A226','description' => 'REINT.DCTO. INDEB. ISLR ENE.98','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A227','description' => 'DIF. SUELDO MES ENERO 1998','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A228','description' => 'RET.DESC.IND.CAPPAUPEL ENERO98','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A229','description' => 'RETROACT.PRIMA ANTIG.ENERO-FEB','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'FD20','description' => 'ASOPROJUPEL MAYO 1998','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A225','description' => 'REINTEGRO PREST.CAPAUPEL MAR','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A234','description' => 'REINT.PRESTAMO CAPAUPEL MARZO','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A233','description' => 'REINT/PRIMA/HIJO FEB-MARZO 98','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A235','description' => 'REINT.LETRA IPAS-ME MARZO 1998','monto'=>'2.5']);		
		DB::table('asignacions')->insert(['codigo' => 'A238','description' => 'REINT/IMP/S/LA RENTA MARZO 98','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A239','description' => 'RETROCT.PJERARQUIA MARZO 1998','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A240','description' => 'REINT. LETRA IPAS-ME MAYO 98','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A241','description' => 'REINT.PRESTAMO CAPAUPEL','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => '9813','description' => 'BONO NOCTURNO MES ABRIL 1998','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A038','description' => 'COMPENSACION POR AJUSTE','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A260','description' => 'CAPPAOUPEL','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A262','description' => 'CAPAUPEL','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A242','description' => 'BONO VACACIONAL','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A243','description' => 'BONO FIN DE AÑO','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A246','description' => 'MONTO BONO MATERIAL DIDACTICO','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A244','description' => 'REIN. LETRA IPAS-ME JUL-AGO.98','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A034','description' => 'AYUD.PARA INCRIP. Y UNIFORMES','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A041','description' => 'BONO NOCTURNO','monto'=>'2.5']);
		DB::table('asignacions')->insert(['codigo' => 'A245','description' => 'DIAS DE ASUETO Y FERIADOS','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A247','description' => 'PRIMA ANTIGUEDAD MES JUNIO 99','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A248','description' => 'BONO PRACTICA PROFESIONAL','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A249','description' => 'DIF.PRIMA HIJO MES MAYO 1999','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A250','description' => 'PRIMA ANTIGUEDAD MES JULIO 99','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A048','description' => 'BONO ALIMENTICIO','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A251','description' => 'BONO VACACIONAL','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A261','description' => 'PRIMA ANTIGUEDAD SEPT.1999','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A263','description' => 'BONO CHOFER','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A252','description' => 'RET. BECAS MES ABRIL 99','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A253','description' => 'PRIMA ANTIGUEDAD OCTUBRE 99','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A254','description' => 'RET.PRIMA HIJO AGOSTO-SEPT.99','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A254','description' => 'PRIMA ANTIGUEDAD MES NOV. 99','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A255','description' => 'PRIMA ANTIGUEDAD FRACCIONADA','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A270','description' => 'BONO COMPENSATORIO','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A256','description' => 'ASIGNACION SUST.HORAS EXTRAS','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A265','description' => 'BONO VACACIONAL 98','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A278','description' => 'AJUSTE DE SUELDO','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A279','description' => 'DIF. PRIMA HIJO','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A280','description' => 'DIF. PRIMA PROFESIONAL','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A281','description' => 'DIF. PRIMA HOGAR','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A282','description' => 'DIF. PRIMA DE TITULAR','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A283','description' => 'DIF. PAGO PRIMA','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A284','description' => 'DIF. PRIMA JERARQUIA','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A257','description' => 'DIFERECIA BONO VACACIONAL','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A289','description' => 'DIF. PRIMA JERARQUIA','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A400','description' => 'R.I.M','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A401','description' => 'REIN. FONDO JUBIL.Y PENS. UPEL','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A402','description' => 'A.M.','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A403','description' => 'REINT. FINANC. PLAN VAC.2001','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A290','description' => 'RET.ANTIG. MES MARZO 2002','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A404','description' => 'ANTICIPO DE PRESTACIONES','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A258','description' => 'PAGO IND. SUELDO POR INCP.','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A405','description' => 'DIF. BONO CHOFER EN VAC. 2000','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A259','description' => 'CESTA TICKET','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A264','description' => 'CESTA TICKET','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A155','description' => 'REIT.IND.P/FORZOSO FEB 2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A156','description' => 'REINT.LEY HABT. FEBRERO 2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A157','description' => 'REINT/S.S.O JULIO 2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A158','description' => 'REINT/PARO FORZOSO JULIO 2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A159','description' => 'REINT/LEY HABIT/JULIO 2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A266','description' => 'PRIMA JERARQUIA JULIO 2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A267','description' => 'PRIMA JERARQUIA DEL 07-07-2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A268','description' => 'PRIMA JERARQUIA DEL 22-07-2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A269','description' => 'PRIMA JERARQUIA DEL 18-07-2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A273','description' => 'PRIMA JERARQUIA DEL 21-07-2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A271','description' => 'PRIMA/JERAR/16-5 AL 30-07-2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A291','description' => 'RE/IMPUESTO S/LA RENTA 2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A292','description' => 'PRIMA JERARQUIA DEL 28-07-2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'FFD2','description' => 'CAPAUPEL DEL 28-07-2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A293','description' => 'P/JERARQUIA 16-9 AL 30-09-2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A294','description' => 'P/JERARQUIA 15-10 AL 30-10-03','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'FD21','description' => 'CAPAUPEL MARZO','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A300','description' => 'HONORARIOS PROFESIONALES','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A301','description' => 'DEUDA 2002-2003','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A009','description' => 'BONO DOCTOR','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A318','description' => 'REINT/SEGURO SOCIAL','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A328','description' => 'BONO COMPENSATORIO','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A302','description' => 'FALLECIMIENTO DEL TRABAJADOR','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A303','description' => 'FALLECIMIENTO DE FAMILIAR','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A304','description' => 'AYUDA MATRIMONIO','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A305','description' => 'AYUDA NACIMIENTO','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A306','description' => 'GUARDERIA','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A348','description' => 'DEUDA 2002-2003 2DA PARTE 25%','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A189','description' => 'PAGO PRIMA JERAR/FEBRERO','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A295','description' => 'FALLECIMIENTO DEL TRABAJADOR','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A350','description' => 'PAGO NIV/SUELDO S.S.O','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A352','description' => 'PAGO NIV/SUELDO PARO FORZOSO','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A353','description' => 'PAGO NIV/SUELDO LEY HABT.','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A354','description' => 'PAGO NIV/SUELDO H.C.M.','monto'=>'3']);
		DB::table('asignacions')->insert(['codigo' => 'A355','description' => 'PAGO NIV/SUELDO CAPPAOUPEL','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A351','description' => 'PAGO NIV/SUELDO SATIUTECPRI','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A406','description' => 'RET.PRIMA HIJO AGOT-SEPT.2007','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A356','description' => 'PAGO NIV/SUELDO ASETA','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A349','description' => 'PAGO NIV/SUELDO F.J.P','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A413','description' => 'PENSION P/ANTIGUEDAD','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A412','description' => 'PENSION RIM','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A308','description' => 'F/JERAR/14-02 AL 29-02-2008','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A307','description' => 'P/JERAR/20-02 AL 29-2-2008','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A309','description' => 'P/JERAR/20-02 AL 30-03-2008','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A310','description' => 'FP/JERAR/18-02 AL 30-03-2008','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A311','description' => 'P/JERARQUIA ABRIL 2008','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A312','description' => 'P/JERARQ/MARZO - ABRIL 2008','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A411','description' => 'PENSION P/HIJO ESPECIAL','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A320','description' => 'BONO SALUD','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A319','description' => 'DIF/8.5% EN PAGO REC/ACAD.','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A313','description' => 'GUARDERIA','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A410','description' => 'PENSION P/HIJO','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'FA32','description' => 'BONO PRODUCCION','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A357','description' => 'RET/AJUSTE B/CHOFER MARZO 09','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A272','description' => 'FONDO ROTATORIO','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A322','description' => 'BONO FAMILIAR','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A323','description' => 'AYUDA ESCOLAR','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A321','description' => 'PRIMA JERARQUIA JUNIO','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A324','description' => 'PRIMA JERARQUIA JUNIO - JULIO','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A409','description' => 'PENSION P/HOGAR','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A329','description' => 'FONDO JUBILACION JULIO 2009','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A001','description' => 'SUELDO MENSUAL','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A015','description' => 'PRIMA JERARQUIA','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A359','description' => 'BONO DE PRODUCCION','monto'=>'5']);
		DB::table('asignacions')->insert(['codigo' => 'A314','description' => 'BONO UNICO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A360','description' => 'PRIMA GRADO/ACADEMICO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A361','description' => 'PRIMA INCENT.AL ESTUDIO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A362','description' => 'DEUDA P/HIJO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A363','description' => 'DEUDA P/HIJOS ESPECIALES','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A325','description' => 'ABONO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A340','description' => 'LAPSO 26-9 AL 30-12-2008','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A341','description' => 'LAPSO 23-10 AL 30-12-2008','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A326','description' => 'DIF/PENSION POR JUBILACION','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A358','description' => '8.5% INTERESES S/P/SOCIALES','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A364','description' => 'P/HIJO ABRIL 2010','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A330','description' => 'FONDO DE JUBILACION','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A415','description' => 'PENSION P/CHOFER','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A414','description' => 'PENSION P/PROFESIONAL','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A416','description' => 'PENSION BONO NOCTURNO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A370','description' => 'REINTEGRO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A371','description' => 'REINTEGRO COMPLEMENTO HCM','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => '1A40','description' => 'PENSION P/TITULAR','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A407','description' => 'PENSION P/JERARQUIA','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A378','description' => 'MATRICULA','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A379','description' => 'REINTEGRO DESCUENTO INBEDIBO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A380','description' => 'RETROACTIVO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A381','description' => 'PENSION AJUSTE SALARIAL','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A408','description' => 'PENSION TITULARIDAD','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A419','description' => 'AJUSTE POR INCREMENTO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A420','description' => 'PENSION P/INCENT.AL EST.','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A421','description' => 'RETROACTIVO P/HIJO','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A430','description' => 'PENSION P/APOYO DOC.INVEST.','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A431','description' => 'RETROAC.PENSION P/APOY.DOC.IN','monto'=>'1']);
		DB::table('asignacions')->insert(['codigo' => 'A432','description' => 'RETROAC.BECA SEPT/OCT2014','monto'=>'1']);

    }
}
