<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class DeduccionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
		//DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('deduccions')->truncate();
        //DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('deduccions')->insert(['codigo' => 'D049','description' => 'PAGO IND/SUELDO','monto'=>'1']);
	    DB::table('deduccions')->insert(['codigo' => 'D052','description' => 'H.C.M.','monto'=>'1']);
	    DB::table('deduccions')->insert(['codigo' => 'D001','description' => 'FONDO DE JUBILACION','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D002','description' => 'SEGURO SOCIAL OBLIGATORIO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D003','description' => 'CUOTA SINDICATO SATIUTECPRI','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D004','description' => 'CUOTA SINDICAL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D005','description' => 'IMPUESTO SOBRE LA RENTA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D006','description' => 'CAPAUPEL MAYO 2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D007','description' => 'INAVI','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D008','description' => 'LA CASA DEL MUEBLE','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D010','description' => 'CAPAUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D012','description' => 'SOCIAL CREDITO MATURIN','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D013','description' => 'IPASME','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D014','description' => 'LETRA DEL IPASME','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D015','description' => 'SEGURO POLIZA ADICIONAL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D016','description' => 'ASETA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D017','description' => 'EMBARGO JUDICIAL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D018','description' => 'DESC/PRIMA JERARQUIA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D019','description' => 'PENSION ALIMENTICIA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D020','description' => 'A.P.R.O.U.P.E.L. SECCIONAL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D022','description' => 'SEGUROS LA SEGURIDAD','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D023','description' => 'AJUSTE PRIMA JERARQUIA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D024','description' => 'COLEGIO DE PROFESORES DE VZLA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D025','description' => 'COLEGIO DE LICENCIADOS DE VZLA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D026','description' => 'CUOTA EXTRAORD/CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D027','description' => 'PARO FORZOSO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D028','description' => 'LEY HABITACIONAL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D029','description' => 'INPRECADES','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D031','description' => 'PRESTAMO ESPECIAL CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D110','description' => 'CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D111','description' => 'PRESTAMO CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D030','description' => 'DESCUENTO POR SALARIO MINIMO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D034','description' => 'CUOTA EXTRAORDIN/','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D035','description' => 'SEGURO DE VIDA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D037','description' => 'ASOPROJUPEL ENERO - MAYO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D038','description' => 'CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D039','description' => 'UNIFORMES CLAUSULA 77','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D041','description' => 'ASIGNACION BECA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D042','description' => 'CUOTA EXTRAORDINARIA ASETA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D043','description' => 'REVISTA DE POST-GRADO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D044','description' => 'PENSION ALIMENTICIA P/HIJO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D045','description' => 'VIATICOS NO CAUSADOS 2001','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D046','description' => 'PAGO IND/REN/CARGO P/JERARQUIA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D047','description' => 'BONO DIDACTICO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D050','description' => 'FINANCIAMENTO PLAN VACACIONAL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D056','description' => 'ASOPROJUPEL MARZO-JUNIO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D057','description' => 'CESTA NAVIDENA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D058','description' => 'COMERCIAL ELARBA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D061','description' => 'PRESTAMO CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D009','description' => 'RECUPERAC.CAPPAOUPEL ENERO 93','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D062','description' => 'H.C.M. JULIO-SEPT. 2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D063','description' => 'SIPROTUPEL-IPM','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D064','description' => 'CASA DEL MUEBLE','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D065','description' => 'SOCIAL CREDITO MATURIN','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D066','description' => 'DIF/HCM JUNIO 2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D068','description' => 'SEGURO H.C.M.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D069','description' => 'DIF. S.S.O. ABRIL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D071','description' => 'PAGO INDEB. P/JEARQUIA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D072','description' => 'DIFERENCIA H.C.M','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D073','description' => 'DESCUENTO PAGO INDEBIDO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D074','description' => 'FONDO AYUDA MUTUA CLUSULA 58','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D075','description' => 'FONDO INST.DE PREV.SOC.DEL PRO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D076','description' => 'PAGO INDEBIDO PJERARQUIA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D078','description' => 'HCM JUNIO - DIC.2002','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D081','description' => 'ASOPROJUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D082','description' => 'PRESTAMO ESPECIAL CAPAUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D083','description' => 'PAGO INDEB.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D085','description' => 'P/JERARQUIA JULO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D033','description' => 'PAGO INDEBIDO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D087','description' => 'ASOPROJUPEL SEPT/NOV.2001','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D088','description' => 'PENSION-UTILES ESCOLARES','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D036','description' => 'CUOTA EXTRAORD.FENASIPRUV','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D021','description' => 'CUOTA EXT/FINANC.CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D080','description' => 'DIF. HCM JULIO 2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D099','description' => 'PENS.-UTILES ESCOL. SEPT. 2000','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D077','description' => 'BOUTIQUE UPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D089','description' => 'CUOTA EXTRAORDINARIA ASETA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D090','description' => 'SEGURO DE VIDA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D091','description' => 'DIF/CAPAUPEL 25-3 AL 31-3-03','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D092','description' => 'PRESTAMO DE AYUDA MUTUA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D093','description' => 'SEGURO GASTOS MORTUORIOS','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D094','description' => 'DIF/FONDO JUB/25-3 AL 31-3-03','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D095','description' => 'GASTOS MORTUORIOS','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D101','description' => 'PENS/ALIM/OMIT/EN BON/VAC.2001','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D096','description' => 'ASOPROJUPEL ABRIL 2000','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D097','description' => 'PAGO INDEB/SUELDO JULIO-NOV.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D098','description' => 'PAGO INDEB/PRIMA TITULAR','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D100','description' => 'PAGO IND.DIF.BONO VPTITULAR','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D102','description' => 'DEUDA SEGURO DE VIDA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D103','description' => 'DEUDA FONDO DE JUB. Y PENSION','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D104','description' => 'ANTICIPO PRIMERA QUINCENA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D112','description' => 'PAGO INDEB SEMESTRE','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D140','description' => 'PAGO PRIMATITULAR ENERO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D105','description' => 'CUOTA ESPECIAL CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D106','description' => 'A.P.R.O.U.P.E.L.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D107','description' => 'PAGO IND/PRIMA TIT/ENERO 2002','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D108','description' => 'DCTO.PAGO IND.PTITULAR EN-FEB','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D109','description' => 'DCTO.PAGO IND.PJERAR. FEBRERO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D114','description' => 'PAGO INDEBIDO SUELDO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D115','description' => 'DIF. HCM DIC. 2004','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D116','description' => 'DIF. CAPPAOUPEL JULIO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D117','description' => 'SEGURO DE VIDA NOVIEMBRE 94','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D118','description' => 'ASOPROJUPEL FEBRERO/ABRIL 2000','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D141','description' => 'PAGO IND.CSINDICAL MARZO 95.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D142','description' => 'PAGO IND.CSINDICAL ABRIL 95.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D113','description' => 'DCTO. PAGO IND.PJERAR.ENE-FEB','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D120','description' => 'COLABORACION ESTUDIANTE','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D121','description' => 'DIF.P/TITULAR ABRIL-MAY-JUN 95','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D122','description' => 'DEUDA H.C.M.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D123','description' => 'ASOPROJUPEL NOV.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D150','description' => 'FDESC. S.S.0 MES ENERO 2002','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D151','description' => 'PAGO IND.PRIMA HIJO EN-JUL.95','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D152','description' => 'FINANCIAMIENTO CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D153','description' => 'PRESTAMO DE AYUDA MUTUA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D154','description' => 'FINANC/CAPPAOUPEL CELULARES','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D155','description' => 'DCTO. EXTRAORDINARIO CAPAUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D156','description' => 'DIF. CUOTA APROUPEL ENERO-DIC.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D157','description' => 'CUOTA EXTRAORDINARIA ASETA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D158','description' => 'PAGO INDEB/BONO TRANSPORTE 95','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D159','description' => 'DIF. HCM  ENERO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D160','description' => 'LIBRERIA AMERICA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D161','description' => 'PAGO/IND/JERAR/28-7 AL 30-9-03','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D162','description' => 'PAGO/IND/P/JERARQ/16-09-2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D163','description' => 'OPTICA LEISCAR C.A.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D164','description' => 'DEC.PAGO IND.PRIMA ANTIGUEDAD','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D165','description' => 'DIF.APROUPEL ENERO FEBRERO 96','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D167','description' => 'REINT. PJER. 2DA.QNA. OCT. 99','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D166','description' => 'PAGO IND.INTE.SOB.PREST SOC.94','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D168','description' => 'DEUDA FONDO DE JUB. Y PENSION','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D169','description' => 'INTER. PREST. HIP. CAPAUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D170','description' => 'LIBRERIA AMERICA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D171','description' => 'PRESTAMO CAPAUPEL JUNIO 96','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D172','description' => 'REINPAGINDDIFSUEL.AGOS.SEP','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D182','description' => 'PRESTAMO ESPECIAL CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D182','description' => 'PRESTAMO ESPECIAL CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D124','description' => 'DIF. H.C.M. OCTUBRE 2004','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D173','description' => 'DIF.SEGURO DE VIDA JUL.-OCT.96','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D174','description' => 'DIF.PENSION ALIM. BONO FIN/AÑO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D023','description' => 'REINT.DESC.IND.LA BOUTIQUE NOV','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D175','description' => 'PENSION DE JUGUETES','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D198','description' => 'CUOTA ESPECIAL SIPROTUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D186','description' => 'PAGO INDGENERACION DE RELEVO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D185','description' => 'INTERNOV.96FINANC.CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D187','description' => 'CUOTA ESPECIAL CAPAUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D189','description' => 'INPRECADES','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D190','description' => 'CAPPAOUPEL FEBRERO/MARZO 2001','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D191','description' => 'DIFC.APROUPEL SEC.ENE-JUN.97','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D232','description' => 'H.C.M. JULIO-AGOSTO DE 1997','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D233','description' => 'DIF./ APRO.SEC. EN-AB-JU-SEP.9','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D234','description' => 'DIF. APROUPEL EN-AB-JU-SEP. 97','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D193','description' => 'CUOTA EXT/ASETA CLAUSULA 16','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D194','description' => 'DIF. S. SOCIAL NOVIEMBRE 1997','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D195','description' => 'DIF. LEY HABITAC. NOVIEM. 1997','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D196','description' => 'ASOPROJUPEL ABRIL-NOVIEM. 97','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D197','description' => 'PAGO INDEB.FONDO DE JUBILACION','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D119','description' => 'PAGO/IND/PRIMA/JERAR/2001','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D240','description' => 'P/HIJO ENERO-JUNIO 2004','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D199','description' => 'DCTO/PAGO IND/NOV/2004','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D201','description' => 'REINT.LETRA IPAS-ME MAYO 98','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D202','description' => 'PENSION P/HIJO FEBRERO-ABRIL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D250','description' => 'DESCUENTO UNICO APROUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D251','description' => 'DCTO. POR PAGO INDEB. P/HIJO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D252','description' => 'ASOPROJUPEL AB-MAY-JUN. 98','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D203','description' => 'PAGO INDEB/PENSION 96,97,98','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D204','description' => 'DESC.EXT.CAPPAOUPEL SEP-NOV.98','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D260','description' => 'DIF.GASTOS MORTUORIOS FEB 1999','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D067','description' => 'DIF. CAPAUPEL ENE-FEB.1999','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D070','description' => 'DIF.FONDO DE JUBI. ENE/FEB 99','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D048','description' => 'EMBARGO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D261','description' => 'PENSION ALIMENTICIA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D125','description' => 'H.C.M. JULIO 2004','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D200','description' => 'PAGO IND/PRIMA TITULAR ENERO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D265','description' => 'COMPLEMENTO HCM','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D266','description' => 'RETRO.COMPLEM.HCM OCT-NOV 1999','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D059','description' => 'PREVISION CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D040','description' => 'PAGO IND. SUELDO JULIO 2000','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D277','description' => 'MONTO COBRADO BONO VACAC.98','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D278','description' => 'PAGO IND/PRIMA/TITULAR SEPT.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D262','description' => 'DEUDA APROUPEL SECCIONAL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D253','description' => 'FINANCIAMIENTO PLAN VACACIONAL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D205','description' => 'FONDO JUB/ENERO 2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D267','description' => 'CAPAUPEL ENERO 2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D254','description' => 'PAGO IND/PRIMA HIJO JUL-OCT.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D255','description' => 'PAGO IND/PRIMA HIJO B.VAC.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D126','description' => 'PENSION UTILES ESCOLARES','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D176','description' => 'CAPPAOUPEL FEBRERO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D177','description' => 'PAGO IND/JERAR/7-7 AL 30-9-03','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D060','description' => 'HCM DICIEMBRE 2002','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D268','description' => 'PENSION ALIMENTICIA ENERO 03','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D127','description' => 'FONDO AYUDA MUTUA CLAUSULA 58','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D129','description' => 'CAPAUPEL DEL 07-07-2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D130','description' => 'CAPAUPEL DEL 22-07-2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D131','description' => 'CAPAUPEL JUNIO-JULIO 2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D132','description' => 'CAPAUPEL DEL 18-07-2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D133','description' => 'CAPAUPEL 16-05 AL 30-07-2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D134','description' => 'PAGO IND/P/JERARQ/21-07-2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D135','description' => 'PAGO IND/P/JERARQ/07-07-2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D136','description' => 'PAGO CAPAUPEL DEL 21-07-2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D128','description' => 'PAGO INDEB. SUELDO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D137','description' => 'ASOPROJUPEL JULIO/SEPT.2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D138','description' => 'ASOPROJUPEL AGOSTO/SEPT.2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D139','description' => 'ASOPROJ/JULIO/AGOSTO/SEPT.2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D291','description' => 'CAPAUPEL DEL 16-9 AL 30-9-2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D280','description' => 'PAGO IND/PRIMA JERARQ/OCTUBRE','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D292','description' => 'CAPAUPEL DEL 15-10 AL 30-10-03','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D295','description' => 'PAGO IND/PRIMA HIJO OCT-NOV.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D293','description' => 'ASOPROJUPEL NOV/2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D296','description' => 'PAGO IND/PRIMA HIJO OCTUBRE','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D206','description' => 'PAGO IND.P/ANTIG.OCT.NOV. 03','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D241','description' => 'PAGO IND/JER/22-11 AL 30-11-03','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D242','description' => 'PAGO IND/JER/22-11 AL 30-11-03','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D207','description' => 'DCTO. PAGO INDB.P/ANTIGUEDAD','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D243','description' => 'PAGO IND/P/JER/26-1 AL 28-2-04','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D208','description' => 'ASOPROJUPEL FEBRERO/MARZO 2004','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D208','description' => 'ASOPROJUPEL MARZO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D500','description' => 'INCLUSION RIM ANTIGUEDAD','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D281','description' => 'DESCTO. PAGO INDEB. DEUDA 50%','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D559','description' => 'DEUDA 50% 2002-2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D566','description' => 'DEUDA 25% 2002-2003','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D143','description' => 'ARC-IPP-UPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D256','description' => 'SEGURO EXCESO CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D257','description' => 'PREVISION FUNERARIA CAPPAOUPEL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D148','description' => 'PAGO IND/CESTA TICKET','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D180','description' => 'PAGO IND/P/JER/20-6 AL 30-6-05','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D181','description' => 'PAGO IND/P/TIRULAR','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D183','description' => 'S.S.O. ENERO-AGOSTO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D184','description' => 'LEY HABITACIONAL FEB-AGOSTO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D188','description' => 'PARO FORZOSO ENERO-AGOSTO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D314','description' => 'ASOPROJUPEL OCTUBRE','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D258','description' => 'PRESTAMO LINEA BLANCA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D319','description' => 'PRIMA JERARQ/10-10 AL 30-11-05','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D320','description' => 'DIF. H.C.M ENERO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D308','description' => 'PAGO P/JER/12-02 AL 28-02-2006','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D309','description' => 'ASOPROJUPEL FEBRERO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D144','description' => 'PAGO IND/SUELDO FEBRERO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D145','description' => 'PAGO IND/PRIMA JERAR/FEB.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D146','description' => 'PAGO IND/PRIMA HIJO FEB.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D210','description' => 'DESC.PAGO/IND.DIF. FEB.2006','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D211','description' => 'PAGO NIV/SUELDO P/ANTIGUEDAD','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D269','description' => 'DES.PAGO/IND.SUELDO MES MARZO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D318','description' => 'ASOPROJUPEL ABRIL - MAYO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D178','description' => 'PAGO P/JERARQUIA ABRIL-MAYO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D147','description' => 'PAGO NIVELACION DE SUELDO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D149','description' => 'PAGO NIVEL/SUELDO P/HIJO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D209','description' => 'PAGO NIVEL/SUELDO P/HIJO ESP.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D212','description' => 'PAGO NIV/SUELDO BECA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D213','description' => 'PAGO NIV/SUEL/AYU/INCRIP.UNIF.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D214','description' => 'PAGO NIV/SUELDO UTILES ESCOL.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D215','description' => 'PAGO NIV/SUELDO JUGUETES','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D216','description' => 'PAGO NIV/SUELDO BONO VAC.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D217','description' => 'PAGO NIV/SUELDO B/DE FIN AÑO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D218','description' => 'PAGO NIV/SUEL/FALLEC/FAMILIAR','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D219','description' => 'PAGO NIV/SUELDO MATRIMONIO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D220','description' => 'PAGO NIV/SUELDO NACIMIENTO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D221','description' => 'PAGO NIVEL/SUELDO ANTIGUEDAD','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D222','description' => 'PAGO NIV/SUELDO 9.5 DIAS','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D223','description' => 'PAGO NIV/SUELDO P/ANTIG.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D322','description' => 'PAGO PRIMA JER/17-4 AL 30-6-06','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D323','description' => 'ASOPROJUPEL ABRIL-JUNIO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D324','description' => 'PAGO PRIMA HIJO ENERO-JUNIO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D321','description' => 'PAGO PRIMA JERAR/ABRIL-JUNIO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D270','description' => 'DIF. H.C.M. JULIO-AGOSTO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D340','description' => 'PAGO P/JERARQ/DEL 16-10-2006','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D271','description' => 'AJUST/P.ANTIG.P/JUBILACION','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D224','description' => 'ASOPROJUPEL ABRIL-MAYO 2007','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D259','description' => 'DCTO. P/HIJO MAYO 2007','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D341','description' => 'PAGO P/JERARQ/DEL 03-07-2007','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D342','description' => 'PAGO P/JERARQ/DEL 04-07-2007','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D345','description' => 'PAGO P/JERAR/25-9 AL 30-10-07','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D346','description' => 'SEGURO SOCIAL OBLIG/OCTUBRE','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D347','description' => 'PARO FORZOSO OCTUBRE','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D348','description' => 'LEY HABITACIONAL OCTUBRE','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D349','description' => 'PAGO P/JERAR/25-9 AL 30-10-07','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D343','description' => 'APROUPEL SEC/JULIO-OCT.2007','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D344','description' => 'APROUPEL JULIO - OCT. 2007','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D350','description' => 'PAGO INDEB. P/PROFESIONAL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D272','description' => 'DESC/PAGO IND.P.ANTIG.NOV.2007','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D351','description' => 'PAGO PRIMA JERAR/20-02-2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D352','description' => 'PAGO PRIMA JERAR/FEBRERO 2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D353','description' => 'PAGO PRIMA JERARQ/18-02-2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D354','description' => 'PAGO DOCENTE BECARIO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D355','description' => 'BONO DIDACTICO DICIEMBRE','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D356','description' => 'P/JERAR 01-01 AL 19-02-2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D357','description' => 'P/JERAR/ENERO-FEBRERO 2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D358','description' => 'P/JERARQ/DEL 1-1 AL 18-02-2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D359','description' => 'DCTO. PAGO INDEB.EN DEUDA 2007','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D360','description' => 'MONTO C/DEUDA HOM/EN-JUN/2007','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D361','description' => 'PAGO P/JERARQUIA ABRIL 2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D362','description' => 'SATIUTECPRI DEUDAD 2006','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D363','description' => 'SATIUTECPRI DEUDA 2007','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D364','description' => 'PAGO P/JERARQ/MARZO-ABRIL 2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D365','description' => 'CAPAUPEL MAYO 2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D366','description' => 'ASOPROJUPEL MAYO 2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D367','description' => 'ASOPROJUPEL MARZO - MAY0 2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D368','description' => 'P/JERAR/DEL 4-06 AL 30-06-2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D369','description' => 'PRIMA JERARQUIA JUNIO 2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D370','description' => 'P/JERAR/DEL 25-6 AL 30-07-2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D371','description' => 'PRIMA JERARQ/15-9 AL 30-9-2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D372','description' => 'P/JER/DIF/HOM/15-09 AL 30-9-08','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D273','description' => 'P/JERAR. OCT-NOV. 2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D274','description' => 'PAGO INDEB.P/HOGAR ENERO 2009','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D275','description' => 'OPTICA','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D276','description' => 'PRIMA JERARQUIA FEBRERO 2009','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D499','description' => 'PAGO INDEV/SUELDO MINIMO 2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D225','description' => 'PAGO P/ADM/23-03 AL 30-03-2009','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D325','description' => 'P/JERARQUIA JUNIO 2009','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D326','description' => 'P/INDEB/BONO VAC/2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D327','description' => 'P/JERARQUIA JUNIO 2009','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D328','description' => 'PLAN VACACIONAL','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D329','description' => 'P/JERARQUIA JULIO 2009','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D330','description' => 'PRIMA JERARQUIA OCTUBRE 2009','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D331','description' => 'PRIMA TITULAR OCT.','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D332','description' => 'IPAS-ME ENERO 2010','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D333','description' => 'SSO ENERO 2010','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D334','description' => 'PARO FORZOSO ENE. 2010','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D335','description' => 'LEY HABITACIONAL ENE. 2010','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D373','description' => 'PRIMA JERARQ/ENERO-FEB/2010','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D374','description' => 'P/GRADO ACADEMICO ENERO 2010','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D375','description' => 'PRIMA JERARQUIA MARZO 2010','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D401','description' => 'ABONO DEUDA ENE-SEP 2008','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D376','description' => 'PAGO INDEB. P/GRADO ACADEMICO','monto'=>'1']);
		DB::table('deduccions')->insert(['codigo' => 'D377','description' => 'FONDO ROTATORIO','monto'=>'1']);
    }
}
